-- 코드를 입력하세요
SELECT YEAR(os.SALES_DATE) as YEAR,	MONTH(os.SALES_DATE) as MONTH, ui.GENDER as GENDER, COUNT(DISTINCT os.USER_ID) AS USERS
FROM ONLINE_SALE as os
LEFT JOIN USER_INFO as ui
ON ui.USER_ID = os.USER_ID
WHERE GENDER is not NULL
GROUP BY YEAR, MONTH, GENDER 
ORDER BY YEAR, MONTH, GENDER

# SELECT *, COUNT(*) AS USERS
# FROM ONLINE_SALE as os
# LEFT JOIN USER_INFO as ui
# ON ui.USER_ID = os.USER_ID
# GROUP BY os.sales_date, ui.gender