SELECT DATE_FORMAT(SALES_DATE, '%Y-%m-%d') as DATE_FORMAT,PRODUCT_ID,USER_ID,SALES_AMOUNT
FROM (SELECT SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT FROM ONLINE_SALE
UNION
SELECT SALES_DATE,PRODUCT_ID,NULL as USER_ID,SALES_AMOUNT FROM OFFLINE_SALE) as t
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-03'
ORDER BY SALES_DATE,PRODUCT_ID,USER_ID
