-- 코드를 입력하세요
SELECT user_id, nickname, CONCAT(CITY,' ',STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소', 
CONCAT(SUBSTRING(TLNO,1,3),'-',SUBSTRING(TLNO,4,4) ,'-',SUBSTRING(TLNO,8,4))AS '전화번호'
FROM USED_GOODS_USER AS user
LEFT JOIN USED_GOODS_BOARD AS board
ON user.user_id = board.writer_id
GROUP BY user_id HAVING count(BOARD_ID) >= 3
ORDER BY USER_ID DESC;