text = input()
text = text.replace('c=','0')
text = text.replace('c-','0')
text = text.replace('dz=','0')
text = text.replace('d-','0')
text = text.replace('lj','0')
text = text.replace('nj','0')
text = text.replace('s=','0')
text = text.replace('z=','0')
print(len(text))