-- 코드를 입력하세요
SELECT ri.REST_ID,	ri.REST_NAME,	ri.FOOD_TYPE,	ri.FAVORITES, ri.ADDRESS, ROUND(AVG(rr.REVIEW_SCORE), 2)AS SCORE 
FROM REST_INFO as ri
JOIN REST_REVIEW as rr
ON ri.REST_ID = rr.REST_ID
GROUP BY ri.REST_ID HAVING ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, ri.FAVORITES DESC;
